### ISSUE TITLE
Alert of Username taken when it is not

### ISSUE THREAD

**Issue by natasha-rgb** [Madi3456/Group-15#92]
I made a new account in the sign up page with my UMass email and it let me get to the intro page but also showed an alert saying the username is taken

**Comment by Madi3456** [comment]
Not sure why that's happening? I've been moving on to the sets to try and get them. Do you mind trying to fix that if you can spot the issue?

**Comment by natasha-rgb** [comment]
Sure, I'll look into it!

**Comment by Madi3456** [comment]
Thank you!

**Comment by natasha-rgb** [comment]
Solved the bug and tested it out. Could you merge the pull request. Thanks!
